server:
  port: 8090

spring:
  application:
    name: gateway-server
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webmvc:
          routes:
            - id: trace-server
              uri: lb://trace-server
              predicates:
                - Path=/api/v1/trace/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/