spring:
  application:
    name: gateway-server
  config:
    import:
      - "optional:configserver:http://34.50.50.170:13100"
      - "optional:file:.env[.properties]"
  cloud:
    gateway:
      server:
        webmvc:
          default-filters:
            - name: jwtGatewayFilter
    config:
      allow-override: true
      override-none: true
      override-system-properties: false
      discovery:
        service-id: config-server
