spring:
  application:
    name: gateway-server
  config:
    import:
      - "optional:configserver"
      - "optional:file:.env[.properties]"
  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: false
      discovery:
        service-id: config-server
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

server:
  port: 8090